# Classification of Iris

## Package imports

In [1]:
# For building neural networks.
import keras as kr

# For interacting with data sets.
import pandas as pd

# For encoding categorical variables.
import sklearn.preprocessing as pre

# For splitting into training and test sets.
import sklearn.model_selection as mod

Using TensorFlow backend.


## Load data

In [2]:
# Load the iris data set from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Inputs

In [4]:
# Separate the inputs from the rest of the variables.
inputs = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]

In [5]:
inputs

petal_length  petal_width  sepal_length  sepal_width
0             1.4          0.2           5.1          3.5
1             1.4          0.2           4.9          3.0
2             1.3          0.2           4.7          3.2
3             1.5          0.2           4.6          3.1
4             1.4          0.2           5.0          3.6
..            ...          ...           ...          ...
145           5.2          2.3           6.7          3.0
146           5.0          1.9           6.3          2.5
147           5.2          2.0           6.5          3.0
148           5.4          2.3           6.2          3.4
149           5.1          1.8           5.9          3.0

[150 rows x 4 columns]

## Encoded outputs

$$
\begin{align*}
  setosa     & \rightarrow  [1,0,0] \\
  versicolor & \rightarrow  [0,1,0] \\
  virginica  & \rightarrow  [0,0,1]
\end{align*}
$$

In [6]:
# Encode the classes as above.
encoder = pre.LabelBinarizer()
encoder.fit(df['species'])
outputs = encoder.transform(df['species'])

outputs

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

## Idea

The neural network will turn four floating point inputs into three "floating point" outputs.

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [0.8, 0.19, 0.01] $$

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [1, 0, 0] $$

## Build model

In [7]:
# Start a neural network, building it by layers.
model = kr.models.Sequential()

# Add a hidden layer with 64 neurons and an input layer with 4.
model.add(kr.layers.Dense(units=64, activation='relu', input_dim=4))
# Add a three neuron output layer.
model.add(kr.layers.Dense(units=3, activation='softmax'))

# Build the graph.
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

## Split

In [8]:
# Split the inputs and outputs into training and test sets.
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.5)

In [9]:
inputs_test.iloc[0]

petal_length    4.7
petal_width     1.2
sepal_length    6.1
sepal_width     2.8
Name: 73, dtype: float64

In [10]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.0524382 , 0.33281925, 0.61474264]], dtype=float32)

## Train

In [11]:
# Train the neural network.
model.fit(inputs_train, outputs_train, epochs=15, batch_size=10)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/15
75/75 [==============================] - 1s 7ms/step - loss: 1.2064 - acc: 0.3467
Epoch 2/15
75/75 [==============================] - 0s 208us/step - loss: 1.0085 - acc: 0.4800
Epoch 3/15
75/75 [==============================] - 0s 417us/step - loss: 0.9250 - acc: 0.6933
Epoch 4/15
75/75 [==============================] - 0s 208us/step - loss: 0.8691 - acc: 0.5867
Epoch 5/15
75/75 [==============================] - 0s 417us/step - loss: 0.8374 - acc: 0.6667
Epoch 6/15
75/75 [==============================] - 0s 208us/step - loss: 0.8117 - acc: 0.7067
Epoch 7/15
75/75 [==============================] - 0s 834us/step - loss: 0.7526 - acc: 0.7867
Epoch 8/15
75/75 [==============================] - 0s 703us/step - loss: 0.7028 - acc: 0.8533
Epoch 9/15
75/75 [==============================] - 0s 833us/step - loss: 0.6743 - acc: 0.8133
Epoch 10/15
75/75 [==============================] - 

## Predict

In [12]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.09503926, 0.34286213, 0.56209856]], dtype=float32)

In [13]:
# Have the network predict the classes of the test inputs.
predictions = model.predict(inputs_test)
predictions_labels = encoder.inverse_transform(predictions)
predictions_labels

array(['virginica', 'versicolor', 'virginica', 'setosa', 'virginica',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'virginica',
       'setosa', 'virginica', 'virginica', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'setosa', 'virginica',
       'setosa', 'virginica', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'virginica', 'virginica',
       'virginica', '

## Evaluate

In [14]:
# Compare the predictions to the actual classes.
predictions_labels == encoder.inverse_transform(outputs_test)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True, False, False,
        True, False, False,  True, False, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True,  True, False, False, False,  True,  True, False,
       False,  True,  True])

In [15]:
(predictions_labels == encoder.inverse_transform(outputs_test)).sum()

51

## End