# Classification of Iris

## Package imports

In [9]:
# For building neural networks.
import keras as kr

# For interacting with data sets.
import pandas as pd

# For encoding categorical variables.
import sklearn.preprocessing as pre

# For splitting into training and test sets.
import sklearn.model_selection as mod

## Load data

In [10]:
# Load the iris data set from a URL.
df = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")

In [11]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Inputs

In [12]:
# Separate the inputs from the rest of the variables.
inputs = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]

In [13]:
inputs

petal_length  petal_width  sepal_length  sepal_width
0             1.4          0.2           5.1          3.5
1             1.4          0.2           4.9          3.0
2             1.3          0.2           4.7          3.2
3             1.5          0.2           4.6          3.1
4             1.4          0.2           5.0          3.6
..            ...          ...           ...          ...
145           5.2          2.3           6.7          3.0
146           5.0          1.9           6.3          2.5
147           5.2          2.0           6.5          3.0
148           5.4          2.3           6.2          3.4
149           5.1          1.8           5.9          3.0

[150 rows x 4 columns]

## Encoded outputs

$$
\begin{align*}
  setosa     & \rightarrow  [1,0,0] \\
  versicolor & \rightarrow  [0,1,0] \\
  virginica  & \rightarrow  [0,0,1]
\end{align*}
$$

In [14]:
# Encode the classes as above.
encoder = pre.LabelBinarizer()
encoder.fit(df['species'])
outputs = encoder.transform(df['species'])

outputs

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

## Idea

The neural network will turn four floating point inputs into three "floating point" outputs.

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [0.8, 0.19, 0.01] $$

$$ [5.1, 3.5, 1.4, 0.2] \rightarrow [1, 0, 0] $$

## Build model

In [15]:
# Start a neural network, building it by layers.
model = kr.models.Sequential()

# Add a hidden layer with 64 neurons and an input layer with 4.
model.add(kr.layers.Dense(units=64, activation='relu', input_dim=4))
# Add a three neuron output layer.
model.add(kr.layers.Dense(units=3, activation='softmax'))

# Build the graph.
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

## Split

In [17]:
# Split the inputs and outputs into training and test sets.
inputs_train, inputs_test, outputs_train, outputs_test = mod.train_test_split(inputs, outputs, test_size=0.5)

In [38]:
inputs_test.iloc[0]

petal_length    4.6
petal_width     1.5
sepal_length    6.5
sepal_width     2.8
Name: 54, dtype: float64

In [39]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.13349593, 0.8232996 , 0.04320448]], dtype=float32)

## Train

In [40]:
# Train the neural network.
model.fit(inputs_train, outputs_train, epochs=15, batch_size=10)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/15
75/75 [==============================] - 1s 16ms/step - loss: 1.0612 - acc: 0.5600
Epoch 2/15
75/75 [==============================] - 0s 1ms/step - loss: 0.7546 - acc: 0.6667
Epoch 3/15
75/75 [==============================] - 0s 651us/step - loss: 0.6854 - acc: 0.7467
Epoch 4/15
75/75 [==============================] - 0s 642us/step - loss: 0.6478 - acc: 0.8000
Epoch 5/15
75/75 [==============================] - 0s 719us/step - loss: 0.6253 - acc: 0.7067
Epoch 6/15
75/75 [==============================] - 0s 1ms/step - loss: 0.5791 - acc: 0.8267
Epoch 7/15
75/75 [==============================] - 0s 808us/step - loss: 0.5805 - acc: 0.8133
Epoch 8/15
75/75 [==============================] - 0s 928us/step - loss: 0.5489 - acc: 0.7733
Epoch 9/15
75/75 [==============================] - 0s 562us/step - loss: 0.5236 - acc: 0.7733
Epoch 10/15
75/75 [==============================] - 0s 

## Predict

In [43]:
model.predict(inputs_test.as_matrix()[0:1])

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0.08331002, 0.39636195, 0.520328  ]], dtype=float32)

In [42]:
# Have the network predict the classes of the test inputs.
predictions = model.predict(inputs_test)
predictions_labels = encoder.inverse_transform(predictions)
predictions_labels

array(['virginica', 'virginica', 'versicolor', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'setosa', 'virginica', 'virginica', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'setosa', 'setosa', 'setosa', 'virginica',
       'virginica', 'virginica', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'virginica', 'virginica',
       'virginica', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 

## Evaluate

In [48]:
# Compare the predictions to the actual classes.
predictions_labels == encoder.inverse_transform(outputs_test)

array([False, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False,  True,  True, False, False, False,  True,  True,
        True, False,  True])

In [47]:
(predictions_labels == encoder.inverse_transform(outputs_test)).sum()

50

## End